[package]
name = "intersection-of-two-arrays"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "intersection_of_two_arrays"
path = "lib.rs"
