[package]
name = "remove-linked-list-elements"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "remove_linked_list_elements"
path = "lib.rs"
