[package]
name = "joi2010ho_a"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "joi2010ho_a"
path = "joi2010ho_a.rs"
