[workspace]
members = ["leetcode/*", "example/*", "aoj/*"]
exclude = [
	"leetcode/0141",
	"leetcode/0142",
	"leetcode/0143",
	"leetcode/0160",
	"leetcode/0430",
	"leetcode/0708",
	"leetcode/0138",
	"leetcode/0116",
	"leetcode/0117",
	"leetcode/0285",
	"leetcode/0157",
]
