[package]
name = "joi2012ho4"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "joi2012ho4"
path = "joi2012ho4.rs"
