[package]
name = "unique-email-addresses"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "unique_email_addresses"
path = "lib.rs"
