[package]
name = "find-k-pairs-with-smallest-sums"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "find_k_pairs_with_smallest_sums"
path = "lib.rs"
