[package]
name = "best-time-to-buy-and-sell-stock-II"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "best_time_to_buy_and_sell_stock_II"
path = "lib.rs"
