[package]
name = "kth-largest-element-in-an-array"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "kth_largest_element_in_an_array"
path = "lib.rs"
