[package]
name = "binary-tree-postorder-traversal"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "binary_tree_postorder_traversal"
path = "lib.rs"
