[package]
name = "k-th-symbol-in-grammar"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "k_th_symbol_in_grammar"
path = "lib.rs"
