[package]
name = "binary-search-tree-iterator"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "binary_search_tree_iterator"
path = "lib.rs"
