[package]
name = "unique-binary-search-trees-II"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "unique_binary_search_trees_II"
path = "lib.rs"
