[package]
name = "subarray-sum-equals-k"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "subarray_sum_equals_k"
path = "lib.rs"
