[package]
name = "maximum-depth-of-binary-tree"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "maximum_depth_of_binary_tree"
path = "lib.rs"
