[package]
name = "two-sum-II-input-array-is-sorted"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "two_sum_II_input_array_is_sorted"
path = "lib.rs"
