[package]
name = "remove-duplicates-from-sorted-list"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "remove_duplicates_from_sorted_list"
path = "lib.rs"
