[package]
name = "itp1_10_a"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "itp1_10_a"
path = "itp1_10_a.rs"
