[package]
name = "s8pc_1_e"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "s8pc_1_e"
path = "s8pc_1_e.rs"
