[package]
name = "joi2011ho1"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "joi2011ho1"
path = "joi2011ho1.rs"
