[package]
name = "delete-node-in-a-bst"
version = "0.1.0"
authors = ["knanao"]
edition = "2021"

# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "delete_node_in_a_bst"
path = "lib.rs"
